language: node_js
node_js:
  - "node"
install:
  - npm i
before scripts:
  - npm run server
script:
  - npm test
  - npm run lint
  - npm run build
  - npm run webpack
  - npm run cypress
after_success:
  - bash <(curl -s https://codecov.io/bash)
