language: node_js
node_js:
  - "node"
install:
  - npm i
  - (cd examples; npm i)
# before_script:
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - sleep 3 # give xvfb some time to start
#   - nohup npm run server  # start a Web server
#   - sleep 3 # give Web server some time to bind to sockets, etc
script:
  - npm test
  - npm run lint
  - npm run build
  - cd examples
  - npm i
  - npm start & npm run cypress

deploy:
  provider: npm
  email: PUBLISHER_EMAIL
  api_key: NPM_AUTH_TOKEN
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
