language: node_js
node_js:
  - "node"
install:
  - npm i
script:
  - npm test
  - npm run lint
  - npm run build
  - npm run docker
  - npm run cypress
after_success:
  - bash <(curl -s https://codecov.io/bash)
