language: node_js
node_js:
  - "node"
install:
  - npm i

script:
  - npm test
  - npm run lint
  - npm run build

deploy:
  provider: npm
  email: PUBLISHER_EMAIL
  api_key: NPM_AUTH_TOKEN
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
